name: Webring

on:
  push:
    branches:
      - main

jobs:
  webring-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Install Guix
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install guix

      - name: Generate
        run: guix environment -C -m manifest.scm -- haunt build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # cname: webring.devse.wiki
